### ISSUE TITLE
Warnings need to be off by default

### ISSUE THREAD

**Issue by laforge49** [alexander-yakushev/defprecated#1]
In a general purpose library, you do not warning printed by default. Warnings should only print when requested, like warn-on-reflection.

To maintain backward compatibility, perhaps something will need to be put in a project file to elicit the new behavior.

**Comment by alexander-yakushev** [comment]
I partly agree, although not sure about the best way to do this. Is there a specific case where the deprecation warnings bother you and you don't control them?

**Comment by laforge49** [comment]
Writing a low-level library as I am, my concern is that some developers
using my library might object to their users getting unanticipated warnings
on out.

Consier for example a program whose output is piped into another program,
and the developer is not even aware that a deprecated warning might be
printed. Could be quite upsetting. And of course, it will occur in the
middle of an important demo or some other particularly bad time.

**Comment by alexander-yakushev** [comment]
I see your point, and I think it will be easier just to print the warnings to stderr. One can usually expect all kinds of things appear in stderr to not rely on it for precise parsing. I personally operate under an assumption that stderr is for devtime and debugging, not for interacting with users. What do you think?

**Comment by laforge49** [comment]
Great idea!

**Comment by alexander-yakushev** [comment]
Thanks for cooperation! I just pushed `0.1.3` which contains the fix.
